{% set name = "diffusers" %}
{% set version = "0.30.3" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/diffusers-{{ version }}.tar.gz
  sha256: 67c5eb25d5b50bf0742624ef43fe0f6d1e1604f64aad3e8558469cbe89ecf72f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - filelock
    - huggingface_hub
    - importlib-metadata
    - numpy
    - pillow
    - regex !=2019.12.17
    - requests
    - pytorch >=1.4
    - safetensors

test:
  imports:
    - diffusers
    - diffusers.models
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/huggingface/diffusers
  summary: Diffusers
  license: Apache-2.0
  license_file: LICENSE
  description: |
    :hugs: Diffusers provides pretrained diffusion models across multiple modalities, 
    such as vision and audio, and serves as a modular toolbox for inference and 
    training of diffusion models.

    PyPI: [https://pypi.org/project/diffusers/](https://pypi.org/project/diffusers/)

  doc_url: https://github.com/huggingface/diffusers
  dev_url: https://github.com/huggingface/diffusers

extra:
  recipe-maintainers:
    - mukhery
    - sugatoray
    # maintainers from upstream repo
    - anton-l
    - patrickvonplaten
